//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyRoyal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\EUR_USD.mdf;I" +
            "ntegrated Security=True")]
        public string bardataConnectionString {
            get {
                return ((string)(this["bardataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=""EC3ABAD797220D664D75276777FD92CB_CES\ONEDRIVE - JOHN MCMAHON ART\PROJECTS\PENNYROYAL\PENNYROYAL\PENNYROYAL\BIN\DEBUG\EUR_USD.MDF"";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string EC3ABAD797220D664D75276777FD92CB_CES_ONEDRIVE___JOHN_MCMAHON_ART_PROJECTS_PENNYROYAL_PENNYROYAL_PENNYROYAL_BIN_DEBUG_EUR {
            get {
                return ((string)(this["EC3ABAD797220D664D75276777FD92CB_CES_ONEDRIVE___JOHN_MCMAHON_ART_PROJECTS_PENNYRO" +
                    "YAL_PENNYROYAL_PENNYROYAL_BIN_DEBUG_EUR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=EUR_USD;Integrated Security=Tr" +
            "ue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string EUR_USDConnectionString {
            get {
                return ((string)(this["EUR_USDConnectionString"]));
            }
        }
    }
}
